Update docs for domain or email verification
Update the docs to reflect the actual functionality.

If you are just testing this out in development and follow the instructions either here or inside the sendgrid web app it never mentions you must first verify a "from" domain or single address. 

You will simply receive a 403 forbidden response on trying to send any mail, including the example email.
The error response does contain an error message though by default it won't be visible due to the way node simplifies deeply nested objects in `console.log`, as you can see below.

```
ResponseError: Forbidden
    at node_modules/@sendgrid/client/src/classes/client.js:133:29
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 403,
  response: {
    headers: {
      server: 'nginx',
      date: 'Fri, 12 Jun 2020 23:54:10 GMT',
      'content-type': 'application/json',
      'content-length': '281',
      connection: 'close',
      'access-control-allow-origin': 'https://sendgrid.api-docs.io',
      'access-control-allow-methods': 'POST',
      'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
      'access-control-max-age': '600',
      'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html'
    },
    body: { errors: [Array] }
  }
}
```

By updating the docs, I think some people will benefit including probably [some people who found their way here](https://github.com/sendgrid/sendgrid-nodejs/issues/957)