Check if "body" on "response" is actually defined before accessing it
Catched this error when testing with a dummy API key.
```
TypeError: Cannot read property 'errors' of undefined
    at ResponseError.toString (.../node_modules/@sendgrid/helpers/classes/response-error.js:45:27)
    at parseStackAndMessage (.../node_modules/bluebird/js/release/debuggability.js:574:25)
    at CapturedTrace.attachExtraTrace (.../node_modules/bluebird/js/release/debuggability.js:778:18)
```
After adding the simple check `if (body && Array.isArray(body.errors))` the "Unauthorized (401)" error is properly returned as promise rejection.